openapi: 3.0.0
info:
  title: Translation Tracker
  description: "This is the API definition for the Translation Tracker."
  version: 1.0.0

servers:
  - url: http://localhost:3000

tags:
  - name: TranslationCases
    description: Create, view, update, and archive translation cases

  - name: TranslationClients
    description: Create, view, update, and archive translation clients

paths:

  /translationCases:
    post:
      tags:
        - TranslationCases
      summary: Create a new translation case (CreateTranslationCaseLambda)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                translationClientId:
                  type: string
                caseNickname:
                  type: string
                projectType:
                  type: string
      responses:
        "200":
          description: A translation case object
          content:
            application/json:
              schema:
                type: object
                properties:
                  translationCaseId:
                    type: string
                  translationClientId:
                    type: string
                  caseNickname:
                    type: string
                  projectType:
                    type: string
                  mostRecentActivity:
                    type: string
                  sourceTextTitle:
                    type: string
                  sourceTextAuthor:
                    type: string
                  translatedTitle:
                    type: string
                  dueDate:
                    type: string
                  startDate:
                    type: string
                  endDate:
                    type: string
                  openCase:
                    type: boolean
                  rushJob:
                    type: boolean
                  progressLog:
                    type: string
                  totalWorkingHours:
                    type: number
                  wordsPerHour:
                    type: number

    get:
      tags:
        - TranslationCases
      summary: Get a list of all translation cases (GetAllTranslationCasesLambda)
      operationId: getAllCases
      responses:
        "200":
          description: A list of translation case objects
          content:
            application/json:
              schema:
                type: object
                properties:
                  translationCaseList:
                    type: array
                    items:
                      properties:
                        translationCaseId:
                          type: string
                        translationClientId:
                          type: string
                        caseNickname:
                          type: string
                        projectType:
                          type: string
                        mostRecentActivity:
                          type: string
                        sourceTextTitle:
                          type: string
                        sourceTextAuthor:
                          type: string
                        translatedTitle:
                          type: string
                        dueDate:
                          type: string
                        startDate:
                          type: string
                        endDate:
                          type: string
                        openCase:
                          type: boolean
                        rushJob:
                          type: boolean
                        progressLog:
                          type: string
                        totalWorkingHours:
                          type: number
                        wordsPerHour:
                          type: number

  /translationCases/{id}:
    get:
      tags:
        - TranslationCases
      summary: Get an existing translation case (GetTranslationCaseLambda)
      parameters:
        - name: id
          in: path
          description: ID of translation case to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: GetTranslationCaseResponse
          content:
            application/json:
              schema:
                type: object
                properties:
                  translationCaseId:
                    type: string
                  translationClientId:
                    type: string
                  caseNickname:
                    type: string
                  projectType:
                    type: string
                  mostRecentActivity:
                    type: string
                  sourceTextTitle:
                    type: string
                  sourceTextAuthor:
                    type: string
                  translatedTitle:
                    type: string
                  dueDate:
                    type: string
                  startDate:
                    type: string
                  endDate:
                    type: string
                  openCase:
                    type: boolean
                  rushJob:
                    type: boolean
                  progressLog:
                    type: string
                  totalWorkingHours:
                    type: number
                  wordsPerHour:
                    type: number
        "500":
          description: "Invalid input parameters"

    put:
      tags:
        -TranslationCases
      summary: Update an existing translation case (UpdateTranslationCaseLambda)
      parameters:
        - name: id
          in: path
          description: ID of translation case to retrieve
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              projectType:
                type: string
              mostRecentActivity:
                type: string
              sourceTextTitle:
                type: string
              sourceTextAuthor:
                type: string
              translatedTitle:
                type: string
              dueDate:
                type: string
              startDate:
                type: string
              endDate:
                type: string
              openCase:
                type: boolean
              rushJob:
                type: boolean
              progressLog:
                type: string
      responses:
        "200":
          description: UpdateTranslationCaseResponse
          content:
            application/json:
              schema:
                type: object
                properties:
                  translationCaseId:
                    type: string
                  translationClientId:
                    type: string
                  caseNickname:
                    type: string
                  projectType:
                    type: string
                  mostRecentActivity:
                    type: string
                  sourceTextTitle:
                    type: string
                  sourceTextAuthor:
                    type: string
                  translatedTitle:
                    type: string
                  dueDate:
                    type: string
                  startDate:
                    type: string
                  endDate:
                    type: string
                  openCase:
                    type: boolean
                  rushJob:
                    type: boolean
                  progressLog:
                    type: string
                  totalWorkingHours:
                    type: number
                  wordsPerHour:
                    type: number
        "500":
          description: "Invalid input parameters"

    delete:
      tags:
        - TranslationCases
      summary: Archive an existing translation case (ArchiveTranslationCaseLambda)
      parameters:
        - name: id
          in: path
          description: ID of translation case to archive
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ArchiveTranslationCaseResponse
          content:
            application/json:
              schema:
                type: object
                properties:
                  translationCaseId:
                    type: string
                  translationClientId:
                    type: string
                  caseNickname:
                    type: string
                  projectType:
                    type: string
                  mostRecentActivity:
                    type: string
                  sourceTextTitle:
                    type: string
                  sourceTextAuthor:
                    type: string
                  translatedTitle:
                    type: string
                  dueDate:
                    type: string
                  startDate:
                    type: string
                  endDate:
                    type: string
                  openCase:
                    type: boolean
                  rushJob:
                    type: boolean
                  progressLog:
                    type: string
                  totalWorkingHours:
                    type: number
                  wordsPerHour:
                    type: number
        "500":
          description: "Invalid input parameters"



  /translationClients:
    post:
      tags:
        - TranslationClients
      summary: Create a new translation client (CreateTranslationClientLambda)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                translationClientName:
                  type: string
                translationClientType:
                  type: string
      responses:
        "200":
          description: A translation client object
          content:
            application/json:
              schema:
                type: object
                properties:
                  translationClientId:
                    type: string
                  translationClientName:
                    type: string
                  translationClientType:
                    type: string
                  mostRecentActivity:
                    type: string

    get:
      tags:
        - TranslationClients
      summary: Get a list of all translation clients (GetAllTranslationClientsLambda)
      operationId: getAllClients
      responses:
        "200":
          description: A list of translation client objects
          content:
            application/json:
              schema:
                type: object
                properties:
                  translationCaseList:
                    type: array
                    items:
                      properties:
                        translationClientId:
                          type: string
                        translationClientName:
                          type: string
                        translationClientType:
                          type: string
                        mostRecentActivity:
                          type: string

  /translationClients/{id}:
    get:
      tags:
        - TranslationClients
      summary: Get an existing translation client (GetTranslationClientsLambda)
      parameters:
        - name: id
          in: path
          description: ID of translation client to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: GetTranslationClientResponse
          content:
            application/json:
              schema:
                type: object
                properties:
                  translationClientId:
                    type: string
                  translationClientName:
                    type: string
                  translationClientType:
                    type: string
                  mostRecentActivity:
                    type: string
        "500":
          description: "Invalid input parameters"

    put:
      tags:
        -TranslationClients
      summary: Update an existing translation client (UpdateTranslationClientLambda)
      parameters:
        - name: id
          in: path
          description: ID of translation client to retrieve
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              translationClientName:
                type: string
              translationClientType:
                type: string
              mostRecentActivity:
                type: string
      responses:
        "200":
          description: UpdateTranslationClientResponse
          content:
            application/json:
              schema:
                type: object
                properties:
                  translationClientId:
                    type: string
                  translationClientName:
                    type: string
                  translationClientType:
                    type: string
                  mostRecentActivity:
                    type: string
        "500":
          description: "Invalid input parameters"

    delete:
      tags:
        - TranslationClients
      summary: Archive an existing translation client (ArchiveTranslationClientLambda)
      parameters:
        - name: id
          in: path
          description: ID of translation client to archive
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ArchiveTranslationClientResponse
          content:
            application/json:
              schema:
                type: object
                properties:
                  translationClientId:
                    type: string
                  translationClientName:
                    type: string
                  translationClientType:
                    type: string
                  mostRecentActivity:
                    type: string
        "500":
          description: "Invalid input parameters"
















